# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(401, 671)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.graph = QtGui.QPushButton(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(170, 520, 131, 51))
        self.graph.setObjectName(_fromUtf8("graph"))
        self.b5 = QtGui.QPushButton(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(100, 220, 61, 51))
        self.b5.setObjectName(_fromUtf8("b5"))
        self.clear = QtGui.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(240, 160, 61, 51))
        self.clear.setObjectName(_fromUtf8("clear"))
        self.b9 = QtGui.QPushButton(self.centralwidget)
        self.b9.setGeometry(QtCore.QRect(170, 160, 61, 51))
        self.b9.setObjectName(_fromUtf8("b9"))
        self.equal = QtGui.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(240, 340, 61, 51))
        self.equal.setObjectName(_fromUtf8("equal"))
        self.b6 = QtGui.QPushButton(self.centralwidget)
        self.b6.setGeometry(QtCore.QRect(170, 220, 61, 51))
        self.b6.setObjectName(_fromUtf8("b6"))
        self.tan = QtGui.QPushButton(self.centralwidget)
        self.tan.setGeometry(QtCore.QRect(170, 400, 61, 51))
        self.tan.setObjectName(_fromUtf8("tan"))
        self.b1 = QtGui.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(30, 280, 61, 51))
        self.b1.setObjectName(_fromUtf8("b1"))
        self.pi = QtGui.QPushButton(self.centralwidget)
        self.pi.setGeometry(QtCore.QRect(310, 460, 61, 51))
        self.pi.setObjectName(_fromUtf8("pi"))
        self.display = QtGui.QLineEdit(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(30, 10, 341, 141))
        self.display.setObjectName(_fromUtf8("display"))
        self.b0 = QtGui.QPushButton(self.centralwidget)
        self.b0.setGeometry(QtCore.QRect(30, 340, 61, 51))
        self.b0.setObjectName(_fromUtf8("b0"))
        self.b_open = QtGui.QPushButton(self.centralwidget)
        self.b_open.setGeometry(QtCore.QRect(30, 460, 61, 51))
        self.b_open.setObjectName(_fromUtf8("b_open"))
        self.substract = QtGui.QPushButton(self.centralwidget)
        self.substract.setGeometry(QtCore.QRect(240, 280, 61, 51))
        self.substract.setObjectName(_fromUtf8("substract"))
        self.ln = QtGui.QPushButton(self.centralwidget)
        self.ln.setGeometry(QtCore.QRect(170, 460, 61, 51))
        self.ln.setObjectName(_fromUtf8("ln"))
        self.multiply = QtGui.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(310, 220, 61, 51))
        self.multiply.setObjectName(_fromUtf8("multiply"))
        self.b4 = QtGui.QPushButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(30, 220, 61, 51))
        self.b4.setObjectName(_fromUtf8("b4"))
        self.power = QtGui.QPushButton(self.centralwidget)
        self.power.setGeometry(QtCore.QRect(240, 400, 61, 51))
        self.power.setObjectName(_fromUtf8("power"))
        self.b3 = QtGui.QPushButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(170, 280, 61, 51))
        self.b3.setObjectName(_fromUtf8("b3"))
        self.b7 = QtGui.QPushButton(self.centralwidget)
        self.b7.setGeometry(QtCore.QRect(30, 160, 61, 51))
        self.b7.setObjectName(_fromUtf8("b7"))
        self.add = QtGui.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(240, 220, 61, 51))
        self.add.setObjectName(_fromUtf8("add"))
        self.b_close = QtGui.QPushButton(self.centralwidget)
        self.b_close.setGeometry(QtCore.QRect(100, 460, 61, 51))
        self.b_close.setObjectName(_fromUtf8("b_close"))
        self.plus_minus = QtGui.QPushButton(self.centralwidget)
        self.plus_minus.setGeometry(QtCore.QRect(100, 340, 61, 51))
        self.plus_minus.setObjectName(_fromUtf8("plus_minus"))
        self.decimal = QtGui.QPushButton(self.centralwidget)
        self.decimal.setGeometry(QtCore.QRect(170, 340, 61, 51))
        self.decimal.setObjectName(_fromUtf8("decimal"))
        self.log = QtGui.QPushButton(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(310, 400, 61, 51))
        self.log.setObjectName(_fromUtf8("log"))
        self.b2 = QtGui.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(100, 280, 61, 51))
        self.b2.setObjectName(_fromUtf8("b2"))
        self.cos = QtGui.QPushButton(self.centralwidget)
        self.cos.setGeometry(QtCore.QRect(100, 400, 61, 51))
        self.cos.setObjectName(_fromUtf8("cos"))
        self.divide = QtGui.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(310, 280, 61, 51))
        self.divide.setObjectName(_fromUtf8("divide"))
        self.e = QtGui.QPushButton(self.centralwidget)
        self.e.setGeometry(QtCore.QRect(240, 460, 61, 51))
        self.e.setObjectName(_fromUtf8("e"))
        self.b8 = QtGui.QPushButton(self.centralwidget)
        self.b8.setGeometry(QtCore.QRect(100, 160, 61, 51))
        self.b8.setObjectName(_fromUtf8("b8"))
        self.sin = QtGui.QPushButton(self.centralwidget)
        self.sin.setGeometry(QtCore.QRect(30, 400, 61, 51))
        self.sin.setObjectName(_fromUtf8("sin"))
        self.sq_root = QtGui.QPushButton(self.centralwidget)
        self.sq_root.setGeometry(QtCore.QRect(310, 340, 61, 51))
        self.sq_root.setObjectName(_fromUtf8("sq_root"))
        self.matrix = QtGui.QPushButton(self.centralwidget)
        self.matrix.setGeometry(QtCore.QRect(30, 520, 131, 51))
        self.matrix.setObjectName(_fromUtf8("matrix"))
        self.back = QtGui.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(310, 160, 61, 51))
        self.back.setObjectName(_fromUtf8("back"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.graph.setText(_translate("MainWindow", "Graph Mode", None))
        self.b5.setText(_translate("MainWindow", "5", None))
        self.clear.setText(_translate("MainWindow", "AC", None))
        self.b9.setText(_translate("MainWindow", "9", None))
        self.equal.setText(_translate("MainWindow", "=", None))
        self.b6.setText(_translate("MainWindow", "6", None))
        self.tan.setText(_translate("MainWindow", "tan", None))
        self.b1.setText(_translate("MainWindow", "1", None))
        self.pi.setText(_translate("MainWindow", "π", None))
        self.b0.setText(_translate("MainWindow", "0", None))
        self.b_open.setText(_translate("MainWindow", "(", None))
        self.substract.setText(_translate("MainWindow", "-", None))
        self.ln.setText(_translate("MainWindow", "ln", None))
        self.multiply.setText(_translate("MainWindow", "X", None))
        self.b4.setText(_translate("MainWindow", "4", None))
        self.power.setText(_translate("MainWindow", "^", None))
        self.b3.setText(_translate("MainWindow", "3", None))
        self.b7.setText(_translate("MainWindow", "7", None))
        self.add.setText(_translate("MainWindow", "+", None))
        self.b_close.setText(_translate("MainWindow", ")", None))
        self.plus_minus.setText(_translate("MainWindow", "+/-", None))
        self.decimal.setText(_translate("MainWindow", ".", None))
        self.log.setText(_translate("MainWindow", "log", None))
        self.b2.setText(_translate("MainWindow", "2", None))
        self.cos.setText(_translate("MainWindow", "cos", None))
        self.divide.setText(_translate("MainWindow", "/", None))
        self.e.setText(_translate("MainWindow", "e", None))
        self.b8.setText(_translate("MainWindow", "8", None))
        self.sin.setText(_translate("MainWindow", "sin", None))
        self.sq_root.setText(_translate("MainWindow", "Sqrt", None))
        self.matrix.setText(_translate("MainWindow", "Matrix mode", None))
        self.back.setText(_translate("MainWindow", "Back", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

