# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(576, 745)
        MainWindow.setMinimumSize(QtCore.QSize(576, 745))
        MainWindow.setMaximumSize(QtCore.QSize(576, 745))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.display = QtGui.QLineEdit(self.frame_2)
        self.display.setMinimumSize(QtCore.QSize(0, 40))
        self.display.setObjectName(_fromUtf8("display"))
        self.gridLayout_2.addWidget(self.display, 0, 0, 1, 5)
        self.b7 = QtGui.QPushButton(self.frame_2)
        self.b7.setMinimumSize(QtCore.QSize(0, 50))
        self.b7.setObjectName(_fromUtf8("b7"))
        self.gridLayout_2.addWidget(self.b7, 1, 0, 1, 1)
        self.b8 = QtGui.QPushButton(self.frame_2)
        self.b8.setMinimumSize(QtCore.QSize(0, 50))
        self.b8.setObjectName(_fromUtf8("b8"))
        self.gridLayout_2.addWidget(self.b8, 1, 1, 1, 1)
        self.b9 = QtGui.QPushButton(self.frame_2)
        self.b9.setMinimumSize(QtCore.QSize(0, 50))
        self.b9.setObjectName(_fromUtf8("b9"))
        self.gridLayout_2.addWidget(self.b9, 1, 2, 1, 1)
        self.clear = QtGui.QPushButton(self.frame_2)
        self.clear.setMinimumSize(QtCore.QSize(0, 50))
        self.clear.setObjectName(_fromUtf8("clear"))
        self.gridLayout_2.addWidget(self.clear, 1, 3, 1, 1)
        self.back = QtGui.QPushButton(self.frame_2)
        self.back.setMinimumSize(QtCore.QSize(0, 50))
        self.back.setObjectName(_fromUtf8("back"))
        self.gridLayout_2.addWidget(self.back, 1, 4, 1, 1)
        self.b4 = QtGui.QPushButton(self.frame_2)
        self.b4.setMinimumSize(QtCore.QSize(0, 50))
        self.b4.setObjectName(_fromUtf8("b4"))
        self.gridLayout_2.addWidget(self.b4, 2, 0, 1, 1)
        self.b5 = QtGui.QPushButton(self.frame_2)
        self.b5.setMinimumSize(QtCore.QSize(0, 50))
        self.b5.setObjectName(_fromUtf8("b5"))
        self.gridLayout_2.addWidget(self.b5, 2, 1, 1, 1)
        self.b6 = QtGui.QPushButton(self.frame_2)
        self.b6.setMinimumSize(QtCore.QSize(0, 50))
        self.b6.setObjectName(_fromUtf8("b6"))
        self.gridLayout_2.addWidget(self.b6, 2, 2, 1, 1)
        self.add = QtGui.QPushButton(self.frame_2)
        self.add.setMinimumSize(QtCore.QSize(0, 50))
        self.add.setObjectName(_fromUtf8("add"))
        self.gridLayout_2.addWidget(self.add, 2, 3, 1, 1)
        self.multiply = QtGui.QPushButton(self.frame_2)
        self.multiply.setMinimumSize(QtCore.QSize(0, 50))
        self.multiply.setObjectName(_fromUtf8("multiply"))
        self.gridLayout_2.addWidget(self.multiply, 2, 4, 1, 1)
        self.b1 = QtGui.QPushButton(self.frame_2)
        self.b1.setMinimumSize(QtCore.QSize(0, 50))
        self.b1.setObjectName(_fromUtf8("b1"))
        self.gridLayout_2.addWidget(self.b1, 3, 0, 1, 1)
        self.b2 = QtGui.QPushButton(self.frame_2)
        self.b2.setMinimumSize(QtCore.QSize(0, 50))
        self.b2.setObjectName(_fromUtf8("b2"))
        self.gridLayout_2.addWidget(self.b2, 3, 1, 1, 1)
        self.b3 = QtGui.QPushButton(self.frame_2)
        self.b3.setMinimumSize(QtCore.QSize(0, 50))
        self.b3.setObjectName(_fromUtf8("b3"))
        self.gridLayout_2.addWidget(self.b3, 3, 2, 1, 1)
        self.substract = QtGui.QPushButton(self.frame_2)
        self.substract.setMinimumSize(QtCore.QSize(0, 50))
        self.substract.setObjectName(_fromUtf8("substract"))
        self.gridLayout_2.addWidget(self.substract, 3, 3, 1, 1)
        self.divide = QtGui.QPushButton(self.frame_2)
        self.divide.setMinimumSize(QtCore.QSize(0, 50))
        self.divide.setObjectName(_fromUtf8("divide"))
        self.gridLayout_2.addWidget(self.divide, 3, 4, 1, 1)
        self.b0 = QtGui.QPushButton(self.frame_2)
        self.b0.setMinimumSize(QtCore.QSize(0, 50))
        self.b0.setObjectName(_fromUtf8("b0"))
        self.gridLayout_2.addWidget(self.b0, 4, 0, 1, 1)
        self.plus_minus = QtGui.QPushButton(self.frame_2)
        self.plus_minus.setMinimumSize(QtCore.QSize(0, 50))
        self.plus_minus.setObjectName(_fromUtf8("plus_minus"))
        self.gridLayout_2.addWidget(self.plus_minus, 4, 1, 1, 1)
        self.decimal = QtGui.QPushButton(self.frame_2)
        self.decimal.setMinimumSize(QtCore.QSize(0, 50))
        self.decimal.setObjectName(_fromUtf8("decimal"))
        self.gridLayout_2.addWidget(self.decimal, 4, 2, 1, 1)
        self.equal = QtGui.QPushButton(self.frame_2)
        self.equal.setMinimumSize(QtCore.QSize(0, 50))
        self.equal.setObjectName(_fromUtf8("equal"))
        self.gridLayout_2.addWidget(self.equal, 4, 3, 1, 1)
        self.sq_root = QtGui.QPushButton(self.frame_2)
        self.sq_root.setMinimumSize(QtCore.QSize(0, 50))
        self.sq_root.setObjectName(_fromUtf8("sq_root"))
        self.gridLayout_2.addWidget(self.sq_root, 4, 4, 1, 1)
        self.sin = QtGui.QPushButton(self.frame_2)
        self.sin.setMinimumSize(QtCore.QSize(0, 50))
        self.sin.setObjectName(_fromUtf8("sin"))
        self.gridLayout_2.addWidget(self.sin, 5, 0, 1, 1)
        self.cos = QtGui.QPushButton(self.frame_2)
        self.cos.setMinimumSize(QtCore.QSize(0, 50))
        self.cos.setObjectName(_fromUtf8("cos"))
        self.gridLayout_2.addWidget(self.cos, 5, 1, 1, 1)
        self.tan = QtGui.QPushButton(self.frame_2)
        self.tan.setMinimumSize(QtCore.QSize(0, 50))
        self.tan.setObjectName(_fromUtf8("tan"))
        self.gridLayout_2.addWidget(self.tan, 5, 2, 1, 1)
        self.power = QtGui.QPushButton(self.frame_2)
        self.power.setMinimumSize(QtCore.QSize(0, 50))
        self.power.setObjectName(_fromUtf8("power"))
        self.gridLayout_2.addWidget(self.power, 5, 3, 1, 1)
        self.log = QtGui.QPushButton(self.frame_2)
        self.log.setMinimumSize(QtCore.QSize(0, 50))
        self.log.setObjectName(_fromUtf8("log"))
        self.gridLayout_2.addWidget(self.log, 5, 4, 1, 1)
        self.b_open = QtGui.QPushButton(self.frame_2)
        self.b_open.setMinimumSize(QtCore.QSize(0, 50))
        self.b_open.setObjectName(_fromUtf8("b_open"))
        self.gridLayout_2.addWidget(self.b_open, 6, 0, 1, 1)
        self.b_close = QtGui.QPushButton(self.frame_2)
        self.b_close.setMinimumSize(QtCore.QSize(0, 50))
        self.b_close.setObjectName(_fromUtf8("b_close"))
        self.gridLayout_2.addWidget(self.b_close, 6, 1, 1, 1)
        self.ln = QtGui.QPushButton(self.frame_2)
        self.ln.setMinimumSize(QtCore.QSize(0, 50))
        self.ln.setObjectName(_fromUtf8("ln"))
        self.gridLayout_2.addWidget(self.ln, 6, 2, 1, 1)
        self.e = QtGui.QPushButton(self.frame_2)
        self.e.setMinimumSize(QtCore.QSize(0, 50))
        self.e.setObjectName(_fromUtf8("e"))
        self.gridLayout_2.addWidget(self.e, 6, 3, 1, 1)
        self.pi = QtGui.QPushButton(self.frame_2)
        self.pi.setMinimumSize(QtCore.QSize(0, 50))
        self.pi.setObjectName(_fromUtf8("pi"))
        self.gridLayout_2.addWidget(self.pi, 6, 4, 1, 1)
        self.fact = QtGui.QPushButton(self.frame_2)
        self.fact.setMinimumSize(QtCore.QSize(0, 50))
        self.fact.setObjectName(_fromUtf8("fact"))
        self.gridLayout_2.addWidget(self.fact, 7, 0, 1, 1)
        self.newmat = QtGui.QPushButton(self.frame_2)
        self.newmat.setMinimumSize(QtCore.QSize(0, 50))
        self.newmat.setObjectName(_fromUtf8("newmat"))
        self.gridLayout_2.addWidget(self.newmat, 7, 1, 1, 1)
        self.addmat = QtGui.QPushButton(self.frame_2)
        self.addmat.setMinimumSize(QtCore.QSize(0, 50))
        self.addmat.setObjectName(_fromUtf8("addmat"))
        self.gridLayout_2.addWidget(self.addmat, 7, 2, 1, 1)
        self.subr_mat = QtGui.QPushButton(self.frame_2)
        self.subr_mat.setMinimumSize(QtCore.QSize(0, 50))
        self.subr_mat.setObjectName(_fromUtf8("subr_mat"))
        self.gridLayout_2.addWidget(self.subr_mat, 7, 3, 1, 1)
        self.mat_mult = QtGui.QPushButton(self.frame_2)
        self.mat_mult.setMinimumSize(QtCore.QSize(0, 50))
        self.mat_mult.setObjectName(_fromUtf8("mat_mult"))
        self.gridLayout_2.addWidget(self.mat_mult, 7, 4, 1, 1)
        self.matinv = QtGui.QPushButton(self.frame_2)
        self.matinv.setMinimumSize(QtCore.QSize(0, 50))
        self.matinv.setObjectName(_fromUtf8("matinv"))
        self.gridLayout_2.addWidget(self.matinv, 8, 0, 1, 1)
        self.sqop = QtGui.QPushButton(self.frame_2)
        self.sqop.setMinimumSize(QtCore.QSize(0, 50))
        self.sqop.setObjectName(_fromUtf8("sqop"))
        self.gridLayout_2.addWidget(self.sqop, 8, 1, 1, 1)
        self.sqcl = QtGui.QPushButton(self.frame_2)
        self.sqcl.setMinimumSize(QtCore.QSize(0, 50))
        self.sqcl.setObjectName(_fromUtf8("sqcl"))
        self.gridLayout_2.addWidget(self.sqcl, 8, 2, 1, 1)
        self.cm = QtGui.QPushButton(self.frame_2)
        self.cm.setMinimumSize(QtCore.QSize(0, 50))
        self.cm.setObjectName(_fromUtf8("cm"))
        self.gridLayout_2.addWidget(self.cm, 8, 3, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.b7.setText(_translate("MainWindow", "7", None))
        self.b8.setText(_translate("MainWindow", "8", None))
        self.b9.setText(_translate("MainWindow", "9", None))
        self.clear.setText(_translate("MainWindow", "AC", None))
        self.back.setText(_translate("MainWindow", "Back", None))
        self.b4.setText(_translate("MainWindow", "4", None))
        self.b5.setText(_translate("MainWindow", "5", None))
        self.b6.setText(_translate("MainWindow", "6", None))
        self.add.setText(_translate("MainWindow", "+", None))
        self.multiply.setText(_translate("MainWindow", "X", None))
        self.b1.setText(_translate("MainWindow", "1", None))
        self.b2.setText(_translate("MainWindow", "2", None))
        self.b3.setText(_translate("MainWindow", "3", None))
        self.substract.setText(_translate("MainWindow", "-", None))
        self.divide.setText(_translate("MainWindow", "/", None))
        self.b0.setText(_translate("MainWindow", "0", None))
        self.plus_minus.setText(_translate("MainWindow", "+/-", None))
        self.decimal.setText(_translate("MainWindow", ".", None))
        self.equal.setText(_translate("MainWindow", "=", None))
        self.sq_root.setText(_translate("MainWindow", "Sqrt", None))
        self.sin.setText(_translate("MainWindow", "sin", None))
        self.cos.setText(_translate("MainWindow", "cos", None))
        self.tan.setText(_translate("MainWindow", "tan", None))
        self.power.setText(_translate("MainWindow", "^", None))
        self.log.setText(_translate("MainWindow", "log", None))
        self.b_open.setText(_translate("MainWindow", "(", None))
        self.b_close.setText(_translate("MainWindow", ")", None))
        self.ln.setText(_translate("MainWindow", "ln", None))
        self.e.setText(_translate("MainWindow", "e", None))
        self.pi.setText(_translate("MainWindow", "π", None))
        self.fact.setText(_translate("MainWindow", "fact", None))
        self.newmat.setText(_translate("MainWindow", "new matrix", None))
        self.addmat.setText(_translate("MainWindow", "+ matrix", None))
        self.subr_mat.setText(_translate("MainWindow", "- matrix", None))
        self.mat_mult.setText(_translate("MainWindow", "mat*mat", None))
        self.matinv.setText(_translate("MainWindow", "mat inverse", None))
        self.sqop.setText(_translate("MainWindow", "[", None))
        self.sqcl.setText(_translate("MainWindow", "]", None))
        self.cm.setText(_translate("MainWindow", ",", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

